name: 'Terraform'

on:
  push:
    branches:
      - main
      - master

jobs:
  terraform:
    name: 'Terraform'
#    env:
#      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
#      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
#      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#      ARM_TENANT_ID:   ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
#    environment: production


#    defaults:
#      run:
#        shell: bash
#        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Terraform
        run: |
          # Download and install the latest version of Terraform
          curl -SL https://releases.hashicorp.com/terraform/1.2.5/terraform_1.2.5_linux_amd64.zip --output terraform_linux.zip
          ls -a
          unzip -o terraform_linux.zip
          mv terraform_linux /usr/local/bin/
          terraform --version
          rm -r terraform_linux.zip

      - name: Install tflink
        run: |
          # Download and install the latest version of tflink
          wget https://github.com/cloudposse/tflink/releases/latest/download/tflink_linux_amd64.zip
          unzip tflink_linux_amd64.zip
          mv tflink /usr/local/bin/
          rm tflink_linux_amd64.zip


      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
         tf_actions_version: 0.14.8
         tf_actions_subcommand: 'fmt'
         tf_actions_working_dir: "./terraform"
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
            tf_actions_version: 0.14.8
            tf_actions_subcommand: 'init'
            tf_actions_working_dir: "./terraform"
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
            tf_actions_version: 0.14.8
            tf_actions_subcommand: 'plan'
            tf_actions_working_dir: "./terraform"
      - name: 'Terraform Apply'
        if: github.ref == 'refs/heads/main'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: "./terraform"
#      - name: 'Terraform Destroy'
#        if: github.ref == 'refs/heads/main'
#        uses: hashicorp/terraform-github-actions@master
#        with:
#            tf_actions_version: 0.14.8
#            tf_actions_subcommand: 'destroy'
#            tf_actions_working_dir: "./terraform"
#
#
#
#
#
#
